name: missionsmate
favicon: null
layout_spectrum: 0.8259973155800253
typography_spectrum: 0.3885769038461149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1693a5'
  brandStrength: 0.47970837145112455
  lightness: 0.7726287464611232
  saturation: 0.10070358449593186
  rhythmicContrast: 0.17403792752884328
purpose: []
